# ThreatLedger MySQL Setup Script
# Run as Administrator: right-click this file -> Run with PowerShell
# (OR run: powershell -ExecutionPolicy Bypass -File "$PSScriptRoot\setup-mysql.ps1")
#
# What this does:
#   1. Installs MySQL Server 8.4 as a Windows service named "MySQL84"
#   2. Starts the service
#   3. Resets the root password from the temp password to "root"
#   4. Creates the `threatledger` database
#   5. Updates Backend/src/main/resources/application.properties to use MySQL instead of H2

$ErrorActionPreference = "Stop"

# --- admin check ---
$identity = [System.Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object System.Security.Principal.WindowsPrincipal($identity)
if (-not $principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "[!] This script must be run as Administrator." -ForegroundColor Red
    Write-Host "    Right-click the file and choose 'Run with PowerShell' from an admin shell," -ForegroundColor Yellow
    Write-Host "    or relaunch PowerShell as Administrator and run:" -ForegroundColor Yellow
    Write-Host "    powershell -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}

$mysqlBase = "C:\Program Files\MySQL\MySQL Server 8.4"
$iniPath  = "C:\ProgramData\MySQL\MySQL Server 8.4\my.ini"
$dataDir = "C:\ProgramData\MySQL\MySQL Server 8.4\Data"
$mysqld  = Join-Path $mysqlBase "bin\mysqld.exe"
$mysql   = Join-Path $mysqlBase "bin\mysql.exe"

# --- locate the temp root password generated by --initialize ---
Write-Host "[*] Locating temporary root password..." -ForegroundColor Cyan
$tempPwd = $null
if (Test-Path "C:\ProgramData\MySQL\init.log") {
    $line = Select-String -Path "C:\ProgramData\MySQL\init.log" -Pattern "temporary password is generated for root@localhost: (.+)$" | Select-Object -Last 1
    if ($line) { $tempPwd = ($line.Matches[0].Groups[1].Value).Trim() }
}
if (-not $tempPwd) {
    Write-Host "[!] Could not find the temp password in init.log." -ForegroundColor Red
    Write-Host "    Re-run mysqld --initialize (see README) or delete the data dir and re-init." -ForegroundColor Yellow
    Read-Host "Press Enter to exit"; exit 1
}
Write-Host "[*] Found temporary password." -ForegroundColor Green

# --- install the service (skipped if already installed) ---
$svc = Get-Service -Name "MySQL84" -ErrorAction SilentlyContinue
if (-not $svc) {
    Write-Host "[*] Installing MySQL84 service..." -ForegroundColor Cyan
    & $mysqld --install "MySQL84" --defaults-file="$iniPath" 2>&1 | Out-Host
    if ($LASTEXITCODE -ne 0) { Write-Host "[!] Service install failed." -ForegroundColor Red; Read-Host "Press Enter to exit"; exit 1 }
} else {
    Write-Host "[*] MySQL84 service already installed." -ForegroundColor DarkGray
}

# --- start the service ---
Write-Host "[*] Starting MySQL84 service..." -ForegroundColor Cyan
Start-Service -Name "MySQL84"
Start-Sleep -Seconds 2
Get-Service -Name "MySQL84" | Select-Object Name, Status, StartType

# --- reset root password to 'root' and create threatledger DB ---
Write-Host "[*] Resetting root password to 'root' and creating 'threatledger' database..." -ForegroundColor Cyan
$alterSql = "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"
$dbSql    = "CREATE DATABASE IF NOT EXISTS threatledger;"
$mysqlOpts = @("--host=localhost", "--port=3306", "--user=root", "--password=$tempPwd", "--connect-expired-password", "-e", $alterSql)
& $mysql @mysqlOpts
if ($LASTEXITCODE -ne 0) {
    Write-Host "[!] Password reset failed (temp password may already have been used/expired)." -ForegroundColor Red
    Write-Host "    If you already changed it, edit this script and set `$tempPwd = 'root' manually." -ForegroundColor Yellow
    Read-Host "Press Enter to exit"; exit 1
}

& $mysql --host=localhost --port=3306 --user=root --password=root -e $dbSql
if ($LASTEXITCODE -ne 0) { Write-Host "[!] Database creation failed." -ForegroundColor Red; Read-Host "Press Enter to exit"; exit 1 }

Write-Host "[*] MySQL ready. root password: root  |  database: threatledger" -ForegroundColor Green

# --- update application.properties to use MySQL instead of H2 ---
$projRoot = Split-Path -Parent $PSScriptRoot
$propsPath = Join-Path $projRoot "Backend\src\main\resources\application.properties"
if (Test-Path $propsPath) {
    Write-Host "[*] Updating $propsPath to use MySQL..." -ForegroundColor Cyan
    $content = Get-Content $propsPath -Raw
    # comment out the 4 H2 lines
    $content = $content -replace '(?m)^(spring\.datasource\.url=jdbc:h2:mem:threatledger)$',  '# $1'
    $content = $content -replace '(?m)^(spring\.datasource\.driver-class-name=org\.h2\.Driver)$', '# $1'
    $content = $content -replace '(?m)^(spring\.datasource\.username=sa)$', '# $1'
    $content = $content -replace '(?m)^(spring\.datasource\.password=)$', '# $1'
    # uncomment the MySQL lines and set password=root
    $content = $content -replace '(?m)^# (spring\.datasource\.url=jdbc:mysql://localhost:3306/threatledger\?createDatabaseIfNotExist=true)$', '$1'
    $content = $content -replace '(?m)^# (spring\.datasource\.username=root)$', '$1'
    $content = $content -replace '(?m)^# (spring\.datasource\.password=)your_mysql_password$', '$1root'
    $content = $content -replace '(?m)^# (spring\.datasource\.driver-class-name=com\.mysql\.cj\.jdbc\.Driver)$', '$1'
    Set-Content -Path $propsPath -Value $content -NoNewline
    Write-Host "[*] application.properties updated to point at MySQL." -ForegroundColor Green
} else {
    Write-Host "[!] application.properties not found at $propsPath" -ForegroundColor Yellow
    Write-Host "    You'll need to edit it manually to switch from H2 to MySQL." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "=================================================" -ForegroundColor Green
Write-Host " MySQL setup complete." -ForegroundColor Green
Write-Host "   Service:    MySQL84 (running, start type: Automatic)" -ForegroundColor Green
Write-Host "   Root user: root   Password: root" -ForegroundColor Green
Write-Host "   Database:   threatledger" -ForegroundColor Green
Write-Host "=================================================" -ForegroundColor Green
Read-Host "Press Enter to exit"
